[
    [
        {"text": " Custom Armor Stands\\n\\n  ", "color": "black"},
        {"text": " ", "bold": True},
        [
            {"text": "To proceed, first\\n ", "color": "gray"},
            {"text": "  ", "bold": True},
            "select the armor\\n   stand you want to\\n        customize.\\n\\n         ",
        ],
        {"text": " ", "bold": True},
        "Select\\n ",
    ],
    [
        {"text": "Nearest Armor Stand\\n    ", "color": "#b26c34"},
        {"text": "   ", "bold": True},
        "Use Mouse",
        {"text": " Custom Armor Stands\\n         ", "color": "black"},
        {"text": " ⤺", "bold": True},
        " ",
        {"text": "⟳", "bold": True},
        " ",
        {"text": "⤻\\n\\n", "bold": True},
        " ",
        {"text": "  ", "bold": True},
        "Manage Selection\\n\\n",
        {"text": " ", "bold": True},
        [
            {"text": "Properties", "color": "#a2462a"},
            {"text": " ", "bold": True},
            "Presets\\n",
            {"text": " ", "bold": True},
            "Clipboard   Slots\\n",
            {"text": " ", "bold": True},
            "Position    ",
            {"text": " ", "bold": True},
            "Rotation\\n\\n  Head   ",
            {"text": "   ", "bold": True},
            "Body\\n  Left Arm  Right Arm\\n  Left Leg  Right Leg",
        ],
        {"text": "⏪  ", "color": "dark_gray"},
        {"text": "Manage Selection ", "color": "black"},
        {"text": "ℹ\\n\\n  ", "color": "#aa0079"},
        {"text": " ", "bold": True},
        "Highlight Selected\\n     ",
        {"text": "   ", "bold": True},
        "Deselect\\n\\n         ",
        {"text": " ", "bold": True},
        {"text": "Select\\n ", "color": "black"},
        "Nearest Armor Stand\\n    ",
        {"text": "   ", "bold": True},
        "Use Mouse",
        [
            {"text": "⏪  ", "color": "dark_gray"},
            {"text": "   ", "bold": True},
            {"text": "Properties     ", "color": "black"},
            {"text": "ℹ\\n\\n", "color": "#aa0079"},
            {"text": "[ ✔ ]", "color": "dark_green"},
            " Base Plate\\n",
            {"text": "[ ✔ ]", "color": "dark_green"},
            " Gravity \\n",
            {"text": "[ ❌ ]", "color": "red"},
            " Invisible\\n",
            {"text": "[ ❌ ]", "color": "red"},
            " Invulnerable\\n",
            {"text": "[ ❌ ]", "color": "red"},
            " Lock Slots\\n",
            {"text": "[ ❌ ]", "color": "red"},
            " Marker\\n",
            {"text": "[ ❌ ]", "color": "red"},
            " Show Arms\\n",
            {"text": "[ ❌ ]", "color": "red"},
            " Show Name Tag\\n",
            {"text": "[ ❌ ]", "color": "red"},
            " Small\\n",
            {"text": "[ ❌ ]", "color": "red"},
            " Visual Fire⏪    ",
        ],
        {"text": "  ", "bold": True},
        {"text": "Clipboard      ", "color": "black"},
        {"text": "ℹ\\n       ", "color": "#aa0079"},
        {"text": "   ", "bold": True},
        "Reset\\n\\n          ",
        {"text": " ", "bold": True},
        {"text": "Copy\\n ", "color": "black"},
        "Properties and Poses\\n   ",
        {"text": " ", "bold": True},
        "Only Properties\\n      ",
        {"text": " ", "bold": True},
        "Only Poses\\n",
        {"text": "  ", "bold": True},
        "Record New Macro\\n\\n       ",
        {"text": "   ", "bold": True},
        {"text": "Paste\\n     ", "color": "black"},
        "Clipboard Data",
        {"text": "⏪        ", "color": "dark_gray"},
        {"text": " ", "bold": True},
        [
            {"text": "Slots     ", "color": "black"},
            {"text": "   ", "bold": True},
            {"text": "ℹ\\n\\n", "color": "#aa0079"},
            "  Swap Main Hand With\\n      ",
        ],
        {"text": "  ", "bold": True},
        "Off-Hand\\n         ",
        {"text": " ", "bold": True},
        "Helmet\\n     ",
        {"text": "  ", "bold": True},
        "Chestplate\\n     ",
        {"text": "   ", "bold": True},
        "Leggings\\n       ",
        {"text": "   ", "bold": True},
        "Boots",
        {"text": "⏪    ", "color": "dark_gray"},
        {"text": "   ", "bold": True},
        {"text": "Position       ", "color": "black"},
        {"text": "ℹ\\n    ", "color": "#aa0079"},
        {"text": "   ", "bold": True},
        "Use Mouse\\n\\n    ",
        {"text": "   ", "bold": True},
        {"text": "Left/Right\\n", "color": "black"},
        {"text": "  -8 -4 -1  ", "color": "#e64c4c"},
        [
            {"text": "+1 +4 +8\\n ", "color": "dark_green"},
            {"text": " ", "bold": True},
            [
                {"text": "Use Mouse ", "color": "#b26c34"},
                {"text": " ", "bold": True},
                "Center\\n\\n",
            ],
            {"text": "         Down/Up\\n", "color": "black"},
            {"text": "  -8 -4 -1  ", "color": "#e64c4c"},
            "+1 +4 +8\\n",
            {"text": "   Use Mouse   Snap\\n\\n    ", "color": "#b26c34"},
            {"text": " ", "bold": True},
            {"text": "Back/Forward\\n", "color": "black"},
            {"text": "  -8 -4 -1  ", "color": "#e64c4c"},
            "+1 +4 +8\\n ",
            {"text": " ", "bold": True},
            [
                {"text": "Use Mouse ", "color": "#b26c34"},
                {"text": " ", "bold": True},
                "Center",
                {"text": "⏪     ", "color": "dark_gray"},
                {"text": "  ", "bold": True},
                {"text": "Rotation   ", "color": "black"},
                {"text": "   ", "bold": True},
                {"text": "ℹ\\n", "color": "#aa0079"},
                "    Flip Horizontally\\n\\n  ",
            ],
            {"text": " ", "bold": True},
            {"text": "Rotate Left/Right\\n", "color": "black"},
            {"text": " ", "bold": True},
            {"text": "-1 -5 -15 -22.5 -90\\n", "color": "#e64c4c"},
            {"text": " ", "bold": True},
            "+1 +5 +15 +22.5 +90\\n    ",
            {"text": "   ", "bold": True},
            {"text": "Use Mouse\\n\\n", "color": "#b26c34"},
            {"text": "  ", "bold": True},
            {"text": "Snap to Multiple of\\n  ", "color": "black"},
            {"text": "  ", "bold": True},
            "5 15 22.5 45 90\\n\\n   ",
            {"text": "   ", "bold": True},
            [
                {"text": "Set Rotation\\n       ", "color": "black"},
                [
                    {"text": "Toward You\\n     Away From You", "color": "#b26c34"},
                    {"text": "⏪    ", "color": "dark_gray"},
                    {"text": "Head ", "color": "black"},
                    {"text": "(1 of 2) ", "color": "gray"},
                    {"text": "  ", "bold": True},
                    {"text": "ℹ\\n", "color": "#aa0079"},
                    {"text": "  ", "bold": True},
                    "Use Mouse",
                    {"text": "  ", "bold": True},
                    "Reset\\n\\n",
                ],
                "        X Rotation\\n",
            ],
            {"text": " ", "bold": True},
            {"text": "-1 -5 -15 -22.5 -90\\n", "color": "#e64c4c"},
            {"text": " ", "bold": True},
            "+1 +5 +15 +22.5 +90\\n",
            {"text": "  ", "bold": True},
            [
                {"text": "Use Mouse", "color": "#b26c34"},
                {"text": "  ", "bold": True},
                "Reset\\n\\n",
            ],
            {"text": "        Y Rotation\\n", "color": "black"},
            {"text": " ", "bold": True},
            {"text": "-1 -5 -15 -22.5 -90\\n", "color": "#e64c4c"},
            {"text": " ", "bold": True},
            "+1 +5 +15 +22.5 +90\\n",
            {"text": "  ", "bold": True},
            [
                {"text": "Use Mouse", "color": "#b26c34"},
                {"text": "  ", "bold": True},
                "Reset",
                {"text": "⏪    ", "color": "dark_gray"},
                {"text": "Head ", "color": "black"},
                {"text": "(2 of 2) ", "color": "gray"},
                {"text": "  ", "bold": True},
                {"text": "ℹ\\n", "color": "#aa0079"},
                {"text": "  ", "bold": True},
                "Use Mouse",
                {"text": "  ", "bold": True},
                "Reset\\n\\n",
            ],
            {"text": "        Z Rotation\\n", "color": "black"},
            {"text": " ", "bold": True},
            {"text": "-1 -5 -15 -22.5 -90\\n", "color": "#e64c4c"},
            {"text": " ", "bold": True},
            "+1 +5 +15 +22.5 +90\\n",
            {"text": "  ", "bold": True},
            [
                {"text": "Use Mouse", "color": "#b26c34"},
                {"text": "  ", "bold": True},
                "Reset\\n\\n   ",
                {"text": "   ", "bold": True},
                {"text": "Set Rotation\\n", "color": "black"},
                {"text": "  ", "bold": True},
                "Toward Your Eyes\\n   Toward Your Feet\\n Away From Your Eyes\\n Away From Your Feet",
                {"text": "⏪", "color": "dark_gray"},
                {"text": " ", "bold": True},
                {"text": "Left Arm", "color": "black"},
                {"text": " ", "bold": True},
                {"text": "(1 of 2)", "color": "gray"},
                {"text": " ", "bold": True},
                {"text": "ℹ\\n", "color": "#aa0079"},
                {"text": "  ", "bold": True},
                "Use Mouse",
                {"text": "  ", "bold": True},
                "Reset\\n    Mirror Right Arm\\n\\n",
            ],
            {"text": "        X Rotation\\n", "color": "black"},
            {"text": " ", "bold": True},
            {"text": "-1 -5 -15 -22.5 -90\\n", "color": "#e64c4c"},
            {"text": " ", "bold": True},
            "+1 +5 +15 +22.5 +90\\n",
            {"text": "  ", "bold": True},
            [
                {"text": "Use Mouse", "color": "#b26c34"},
                {"text": "  ", "bold": True},
                "Reset\\n\\n",
            ],
            {"text": "        Y Rotation\\n", "color": "black"},
            {"text": " ", "bold": True},
            {"text": "-1 -5 -15 -22.5 -90\\n", "color": "#e64c4c"},
            {"text": " ", "bold": True},
            "+1 +5 +15 +22.5 +90\\n",
            {"text": "  ", "bold": True},
            [
                {"text": "Use Mouse", "color": "#b26c34"},
                {"text": "  ", "bold": True},
                "Reset",
                {"text": "⏪", "color": "dark_gray"},
                {"text": " ", "bold": True},
                {"text": "Left Arm", "color": "black"},
                {"text": " ", "bold": True},
                {"text": "(2 of 2)", "color": "gray"},
                {"text": " ", "bold": True},
                {"text": "ℹ\\n", "color": "#aa0079"},
                {"text": "  ", "bold": True},
                "Use Mouse",
                {"text": "  ", "bold": True},
                "Reset\\n    Mirror Right Arm\\n\\n",
            ],
            {"text": "        Z Rotation\\n", "color": "black"},
            {"text": " ", "bold": True},
            {"text": "-1 -5 -15 -22.5 -90\\n", "color": "#e64c4c"},
            {"text": " ", "bold": True},
            "+1 +5 +15 +22.5 +90\\n",
        ],
        {"text": "  ", "bold": True},
        "Use Mouse",
        {"text": "  ", "bold": True},
        "Reset\\n\\n   ",
        {"text": "   ", "bold": True},
        {"text": "Set Rotation\\n", "color": "black"},
        {"text": "  ", "bold": True},
        "Toward Your Eyes\\n   Toward Your Feet\\n Away From Your Eyes\\n Away From Your Feet",
    ],
]
